/*
 * generated by Xtext 2.24.0
 */
package org.big.erd.validation
import org.big.erd.entityRelationship.Model
import org.eclipse.xtext.validation.Check
import org.big.erd.entityRelationship.CardinalityType
import org.big.erd.entityRelationship.RelationEntity
import org.big.erd.entityRelationship.NotationType
import org.eclipse.xtext.validation.ComposedChecks
import org.big.erd.entityRelationship.Entity
import org.big.erd.entityRelationship.AttributeType
import static org.big.erd.entityRelationship.EntityRelationshipPackage.Literals.*
import org.big.erd.entityRelationship.Relationship
import org.big.erd.entityRelationship.RelationshipType
import org.big.erd.entityRelationship.VisibilityType
import org.big.erd.entityRelationship.Attribute
import org.big.erd.entityRelationship.Hierarchy
import org.big.erd.entityRelationship.HierarchyCompleteness
import org.eclipse.xtext.nodemodel.util.NodeModelUtils

/**
 * Custom ValidationRules with composed checks 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation for documentation
 */
@ComposedChecks(validators=#[
	NamingValidator
])
class EntityRelationshipValidator extends AbstractEntityRelationshipValidator {

	public static final String UNSUPPORTED_NOTATION = "unsupportedNotation";
	public static final String MISSING_PRIMARY_KEY = "missingPrimaryKey";
	public static final String MISSING_PARTIAL_KEY = "missingPartialKey";
	public static final String INVALID_CARDINALITY = "invalidCardinality";
	
	public static final String HIERARCHY_WITHOUT_SUBCLASSES = "hierarchyWithoutSubclasses";
	public static final String INVALID_SINGLE_SUBCLASS_HIERARCHY = "invalidSingleSubclassHierarchy";
	public static final String MISSING_HIERARCHY_CONSTRAINT = "missingHierarchyConstraint";
	public static final String DUPLICATE_HIERARCHY_NAME = "duplicateHierarchyName";
	public static final String INVALID_HIERARCHY_BASE = "invalidHierarchyBase";
	public static final String INVALID_HIERARCHY_CYCLE = "invalidHierarchyCycle";
	public static final String INVALID_SUBCLASS_KEY = "invalidSubclassKey";
	public static final String INVALID_ASSOCIATIVE_KEY = "invalidAssociativeKey";
	
	@Check
	def checkKeys(Entity entity) {
		if (entity.associative) {
			val hasKey = entity.attributes.exists[
				it.type === AttributeType.KEY
			]

			val hasPartialKey = entity.attributes.exists[
				it.type === AttributeType.PARTIAL_KEY
			]

			if (hasKey || hasPartialKey) {
				error(
					'''Associative entities cannot declare key or partial-key attributes''',
					entity,
					ENTITY__ATTRIBUTES,
					INVALID_ASSOCIATIVE_KEY
				)
			}

			return
		}

		if (entity.weak) {
			if (entity.attributes?.filter[it.type === AttributeType.PARTIAL_KEY].isNullOrEmpty) {
				warning(
					'''Missing partial key for weak entity''',
					entity,
					ENTITY__ATTRIBUTES,
					MISSING_PARTIAL_KEY
				)
			}
		} else {
			if (entity.attributes?.filter[it.type === AttributeType.KEY].isNullOrEmpty) {
				warning(
					'''Missing primary key for entity''',
					entity,
					ENTITY__ATTRIBUTES,
					MISSING_PRIMARY_KEY
				)
			}
		}
	}

	@Check
	def checkHierarchy(Hierarchy hierarchy) {
		val container = hierarchy.eContainer

		if (container instanceof Model) {
			val model = container

			// Entidades que pertenecen directamente a esta jerarquía
			val subclasses = model.entities.filter[
				it.extends === hierarchy
			].toList

			// Comprueba si disjoint u overlapping se ha escrito explícitamente
			val hasConstraint = !NodeModelUtils.findNodesForFeature(
				hierarchy,
				HIERARCHY__CONSTRAINT
			).empty

			// Toda jerarquía debe tener al menos una subclase
			if (subclasses.empty) {
				error(
					'''Hierarchy '«hierarchy.name»' must have at least one subclass''',
					hierarchy,
					HIERARCHY__NAME,
					HIERARCHY_WITHOUT_SUBCLASSES
				)
			}

			// Con una única subclase solo se admite "partial"
			if (subclasses.size == 1) {
				if (hierarchy.completeness != HierarchyCompleteness.PARTIAL ||
					hasConstraint) {

					error(
					'''A hierarchy with a single subclass must be declared only as partial''',
						hierarchy,
						HIERARCHY__COMPLETENESS,
						INVALID_SINGLE_SUBCLASS_HIERARCHY
					)
				}
			}

			// Con dos o más subclases es obligatorio indicar
			// disjoint u overlapping
			if (subclasses.size >= 2 && !hasConstraint) {
				error(
				'''A hierarchy with two or more subclasses must specify disjoint or overlapping''',
					hierarchy,
					HIERARCHY__COMPLETENESS,
					MISSING_HIERARCHY_CONSTRAINT
				)
			}

			// El nombre de la jerarquía debe ser único globalmente
			val duplicateHierarchy = model.hierarchies.exists[
				it !== hierarchy && it.name == hierarchy.name
			]

			val duplicateEntity = model.entities.exists[
				it.name == hierarchy.name
			]

			val duplicateRelationship = model.relationships.exists[
				it.name == hierarchy.name
			]

			if (duplicateHierarchy || duplicateEntity || duplicateRelationship) {
				error(
					'''Name '«hierarchy.name»' is already used by another model element''',
					hierarchy,
					HIERARCHY__NAME,
					DUPLICATE_HIERARCHY_NAME
				)
			}

			// Una entidad débil no puede actuar como raíz de una jerarquía
			if (hierarchy.base !== null && hierarchy.base.weak) {
				error(
					'''Weak entity '«hierarchy.base.name»' cannot be the base of a hierarchy''',
					hierarchy,
					HIERARCHY__BASE,
					INVALID_HIERARCHY_BASE
				)
			}

			// Una entidad asociativa no puede actuar como raíz de una jerarquía
			if (hierarchy.base !== null && hierarchy.base.associative) {
				error(
					'''Associative entity '«hierarchy.base.name»' cannot be the base of a hierarchy''',
					hierarchy,
					HIERARCHY__BASE,
					INVALID_HIERARCHY_BASE
				)
			}

			// Comprueba que la jerarquía no introduzca un ciclo
			if (hierarchy.base !== null && createsHierarchyCycle(hierarchy)) {
				error(
					'''Hierarchy '«hierarchy.name»' introduces an inheritance cycle''',
					hierarchy,
					HIERARCHY__BASE,
					INVALID_HIERARCHY_CYCLE
				)
			}
		}
	}

	@Check
	def checkSubclassKey(Entity entity) {
		if (entity.extends === null || entity.extends.base === null) {
			return
		}

		val superEntity = entity.extends.base

		val subclassKeys = entity.attributes
			.filter[it.type === AttributeType.KEY]
			.map[it.name]
			.toSet

		val superKeys = superEntity.attributes
			.filter[it.type === AttributeType.KEY]
			.map[it.name]
			.toSet

		if (subclassKeys != superKeys) {
			error(
				'''Subclass '«entity.name»' must declare the same key as superclass '«superEntity.name»' ''',
				entity,
				ENTITY__ATTRIBUTES,
				INVALID_SUBCLASS_KEY
			)
		}
	}
	
	@Check
	def checkRelationEntity(RelationEntity relation) {
		val model = relation.eContainer.eContainer
		if (model instanceof Model) {
			val notation = model.notation?.notationType
			if (notation !== null) {
				if (notation.equals(NotationType.BACHMAN) ||
					notation.equals(NotationType.CHEN) ||
					notation.equals(NotationType.CROWSFOOT)
				) {
					checkCardinality(relation)
				}
			}
		}
	}
	
	def checkCardinality(RelationEntity relation) {
		switch relation.cardinality {
    		case CardinalityType.ZERO_OR_ONE,
    		case CardinalityType.ZERO_OR_MORE,
    		case CardinalityType.ONE,
    		case CardinalityType.MANY: return
    		default: warning(
    			'''Invalid cardinality for '«relation.target.name»'!«'\n\n'»Use [0..1], [0..N], [1] or [N]''',
    			relation,
    			RELATION_ENTITY__CARDINALITY,
    			INVALID_CARDINALITY
    		)
    	}
	}

	def boolean createsHierarchyCycle(Hierarchy hierarchy) {
		val visited = newHashSet

		var Entity current = hierarchy.base

		while (current !== null) {
			if (!visited.add(current)) {
				return true
			}

			if (current.extends === null) {
				return false
			}

			current = current.extends.base
		}

		return false
	}
	
	@Check
	def checkAggregation(Relationship relationship) {
		val model = relationship.eContainer
		if (model instanceof Model) {
			val notation = model.notation?.notationType
			if(notation === null){
				return
			}
			if (notation !== null) {
				if(notation.equals(NotationType.UML)){
					if(!relationship.firstType.equals(RelationshipType.DEFAULT) &&
					   !relationship.secondType.equals(RelationshipType.DEFAULT)){
						warning('''Aggregation only supported for UML''', relationship, RELATIONSHIP__SECOND_TYPE)
					}
				}else{
					if(!relationship.firstType.equals(RelationshipType.DEFAULT)){
						warning('''Aggregation only supported for UML''', relationship, RELATIONSHIP__FIRST_TYPE)
					}
					if(!relationship.secondType.equals(RelationshipType.DEFAULT)){
						warning('''Aggregation only supported for UML''', relationship, RELATIONSHIP__SECOND_TYPE)
					}
				}
			}
		}
	}
	
	@Check
	def checkVisibility(Attribute attribute) {
		val model = attribute.eContainer.eContainer
		if (model instanceof Model) {
			val notation = model.notation?.notationType
			if(notation !== null && !notation.equals(NotationType.UML) && !attribute.visibility.equals(VisibilityType.NONE)){
				warning('''Use visibility operators only for UML''', attribute, ATTRIBUTE__VISIBILITY)
		
			}
		}
	}
}
